-- Run this in your Supabase SQL Editor to create the required tables

-- 1. Reading Labs Table
CREATE TABLE reading_labs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage TEXT NOT NULL,
  questions JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Grammar Labs Table
CREATE TABLE grammar_labs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL,
  question JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Skills Labs Table
CREATE TABLE skills_labs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL,
  question JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add simple Row Level Security (RLS) policies for anonymous read access
ALTER TABLE reading_labs ENABLE ROW LEVEL SECURITY;
ALTER TABLE grammar_labs ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills_labs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read access reading_labs" ON reading_labs FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert reading_labs" ON reading_labs FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous read access grammar_labs" ON grammar_labs FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert grammar_labs" ON grammar_labs FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous read access skills_labs" ON skills_labs FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert skills_labs" ON skills_labs FOR INSERT WITH CHECK (true);

-- 4. Vocab Labs Table
CREATE TABLE vocab_labs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode TEXT NOT NULL,
  question JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE vocab_labs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous read access vocab_labs" ON vocab_labs FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert vocab_labs" ON vocab_labs FOR INSERT WITH CHECK (true);
